server:
  port: 8082

node:
  id: NODE_B
  neighbors:
    - id: NODE_A
      url: ws://localhost:8081/ws/peer
    - id: NODE_C
      url: ws://localhost:8083/ws/peer

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messlink_node_b
    username: postgres
    password: Radhika@123
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    com.messlink: DEBUG
