server:
  port: 8081

node:
  id: ${NODE_ID:NODE_A}
  neighbors:
    - id: NODE_B
      url: ${NODE_B_WS_URL:ws://localhost:8082/ws/peer}
    - id: NODE_C
      url: ${NODE_C_WS_URL:ws://localhost:8083/ws/peer}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/messlink_node_a}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    com.messlink: DEBUG